#  Data Cleaning Ola Ride Booking Analytics

In [4]:
#import libraries
import pandas as pd
import numpy as np

In [5]:
df=pd.read_excel("Bookings-20000-Rows.xlsx")
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0

In [6]:
df.shape

(20407, 19)

In [7]:
df.columns

Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'V_TAT', 'C_TAT',
       'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver',
       'Incomplete_Rides', 'Incomplete_Rides_Reason', 'Booking_Value',
       'Payment_Method', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20407 entries, 0 to 20406
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        20407 non-null  datetime64[ns]
 1   Time                        20407 non-null  object
 2   Booking_ID                  20407 non-null  object
 3   Booking_Status              20407 non-null  object
 4   Customer_ID                 20407 non-null  object
 5   Vehicle_Type                20407 non-null  object
 6   Pickup_Location             20407 non-null  object
 7   Drop_Location               20407 non-null  object
 8   V_TAT                       12652 non-null  float64
 9   C_TAT                       12652 non-null  float64
 10  Canceled_Rides_by_Customer  2081 non-null   object
 11  Canceled_Rides_by_Driver    3654 non-null   object
 12  Incomplete_Rides            12652 non-null  object
 13  Incomplete_Rides_Reason     795 non-null    object
 14  Booking_Value               20407 non-null  int64
 15  Payment_Method              12652 non-null  object
 16  Ride_Distance               20407 non-null  int64
 17  Driver_Ratings              12652 non-null  float64
 18  Customer_Rating             12652 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(2), object(12)
memory usage: 3.0+ MB

In [9]:
df.describe()

,Date,V_TAT,C_TAT,Booking_Value,Ride_Distance,Driver_Ratings,Customer_Rating
count,20407,12652.000000,12652.000000,20407.000000,20407.000000,12652.000000,12652.000000
mean,2024-07-15 23:51:58.418189824,170.640768,85.183765,546.316019,14.160386,3.997479,3.993772
min,2024-07-01 00:02:00,35.000000,25.000000,100.000000,0.000000,3.000000,3.000000
25%,2024-07-08 12:42:00,98.000000,55.000000,240.000000,0.000000,3.500000,3.500000
50%,2024-07-15 23:58:00,168.000000,85.000000,384.000000,8.000000,4.000000,4.000000
75%,2024-07-23 12:07:30,238.000000,115.000000,623.000000,27.000000,4.500000,4.500000
max,2024-07-30 23:56:00,308.000000,145.000000,2999.000000,49.000000,5.000000,5.000000
std,NaN,80.657316,35.993634,533.593923,15.827246,0.576357,0.581111

## Check Missing Values

In [10]:
df.isnull().sum()

Date                              0
Time                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                          7755
C_TAT                          7755
Canceled_Rides_by_Customer    18326
Canceled_Rides_by_Driver      16753
Incomplete_Rides               7755
Incomplete_Rides_Reason       19612
Booking_Value                     0
Payment_Method                 7755
Ride_Distance                     0
Driver_Ratings                 7755
Customer_Rating                7755
dtype: int64

In [13]:
# Fill null values
cols = [
    "Canceled_Rides_by_Customer",
    "Canceled_Rides_by_Driver",
    "Incomplete_Rides_Reason",
     "Payment_Method"
]

for col in cols:
    df[col] = df[col].fillna("Not Applicable")

In [14]:
df[cols].isnull().sum()

Canceled_Rides_by_Customer    0
Canceled_Rides_by_Driver      0
Incomplete_Rides_Reason       0
Payment_Method                0
dtype: int64

In [15]:
df["Incomplete_Rides"] = df["Incomplete_Rides"].fillna("No")

In [16]:
df.isnull().sum()

Date                             0
Time                             0
Booking_ID                       0
Booking_Status                   0
Customer_ID                      0
Vehicle_Type                     0
Pickup_Location                  0
Drop_Location                    0
V_TAT                         7755
C_TAT                         7755
Canceled_Rides_by_Customer       0
Canceled_Rides_by_Driver         0
Incomplete_Rides                 0
Incomplete_Rides_Reason          0
Booking_Value                    0
Payment_Method                   0
Ride_Distance                    0
Driver_Ratings                7755
Customer_Rating               7755
dtype: int64

In [17]:
cols = [
    "V_TAT",
    "C_TAT",
    "Driver_Ratings",
    "Customer_Rating"
]

for col in cols:
    df[col] = df[col].fillna(0)

In [18]:
df[cols].isnull().sum()

V_TAT              0
C_TAT              0
Driver_Ratings     0
Customer_Rating    0
dtype: int64

In [19]:
df.isnull().sum()

Date                          0
Time                          0
Booking_ID                    0
Booking_Status                0
Customer_ID                   0
Vehicle_Type                  0
Pickup_Location               0
Drop_Location                 0
V_TAT                         0
C_TAT                         0
Canceled_Rides_by_Customer    0
Canceled_Rides_by_Driver      0
Incomplete_Rides              0
Incomplete_Rides_Reason       0
Booking_Value                 0
Payment_Method                0
Ride_Distance                 0
Driver_Ratings                0
Customer_Rating               0
dtype: int64

##  Check duplicate Record

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df=df.drop_duplicates()
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,0.0,0.0,Not Applicable,Personal & Car related issue,No,Not Applicable,444,Not Applicable,0,0.0,0.0
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,Not Applicable,Not Applicable,No,Not Applicable,158,Cash,13,4.1,4.0
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,Not Applicable,Not Applicable,No,Not Applicable,386,UPI,40,4.2,4.8
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,0.0,0.0,Driver is not moving towards pickup location,Not Applicable,No,Not Applicable,384,Not Applicable,0,0.0,0.0
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,Not Applicable,Not Applicable,No,Not Applicable,822,Credit Card,45,4.0,3.0

## Cleaning Data Types

In [22]:
df.dtypes

Date                          datetime64[ns]
Time                                  object
Booking_ID                            object
Booking_Status                        object
Customer_ID                           object
Vehicle_Type                          object
Pickup_Location                       object
Drop_Location                         object
V_TAT                                float64
C_TAT                                float64
Canceled_Rides_by_Customer            object
Canceled_Rides_by_Driver              object
Incomplete_Rides                      object
Incomplete_Rides_Reason               object
Booking_Value                          int64
Payment_Method                        object
Ride_Distance                          int64
Driver_Ratings                       float64
Customer_Rating                      float64
dtype: object

##  Booking Status Check

In [23]:
df['Booking_Status'].value_counts()

Booking_Status
Success                 12652
Canceled by Driver       3654
Canceled by Customer     2081
Driver Not Found         2020
Name: count, dtype: int64

##  Categorical Columns Check

In [24]:
categorical_cols = [
    'Booking_Status',
    'Payment_Method',
    'Vehicle_Type',
    'Pickup_Location',
    'Drop_Location',
]

for col in categorical_cols:
    print("\n", col)
    print(df[col].value_counts(dropna=False))

 Booking_Status
Booking_Status
Success                 12652
Canceled by Driver       3654
Canceled by Customer     2081
Driver Not Found         2020
Name: count, dtype: int64

 Payment_Method
Payment_Method
Not Applicable    7755
Cash              6934
UPI               5113
Credit Card        480
Debit Card         125
Name: count, dtype: int64

 Vehicle_Type
Vehicle_Type
eBike          2997
Bike           2949
Prime Sedan    2945
Prime SUV      2945
Auto           2916
Mini           2867
Prime Plus     2788
Name: count, dtype: int64

 Pickup_Location
Pickup_Location
Sarjapur Road           445
KR Puram                442
Kammanahalli            438
Banashankari            438
Peenya                  437
JP Nagar                434
Kengeri                 433
RT Nagar                433
Tumkur Road             430
Magadi Road             430
Mysore Road             425
Cox Town                422
Electronic City         420
Nagarbhavi              419
Ramamurthy Nagar        417
Jayanagar               417
Indiranagar             417
Chickpet                416
Malleshwaram            415
BTM Layout              413
Vijayanagar             411
Shantinagar             411
Sahakar Nagar           410
Bannerghatta Road       407
Marathahalli            406
Basavanagudi            405
Langford Town           404
Devanahalli             403
Chamarajpet             403
Yelahanka               403
HSR Layout              401
Whitefield              400
Majestic                400
Shivajinagar            398
Rajarajeshwari Nagar    398
Bellandur               397
Hosur Road              396
Kadugodi                395
Varthur                 394
Frazer Town             393
Ulsoor                  391
Richmond Town           389
Koramangala             387
Padmanabhanagar         386
Hennur                  386
Rajajinagar             385
Yeshwanthpur            382
MG Road                 376
Hebbal                  375
Hulimavu                374
Name: count, dtype: int64

 Drop_Location
Drop_Location
Majestic                456
HSR Layout              443
Kengeri                 435
Marathahalli            432
BTM Layout              430
Mysore Road             429
Peenya                  428
Tumkur Road             427
Sarjapur Road           427
Shantinagar             426
Langford Town           422
Koramangala             422
Shivajinagar            422
Bannerghatta Road       422
Vijayanagar             421
RT Nagar                421
Kadugodi                419
JP Nagar                418
Rajarajeshwari Nagar    418
Malleshwaram            415
Hennur                  414
MG Road                 414
Rajajinagar             413
Electronic City         409
Sahakar Nagar           408
Hosur Road              407
Hebbal                  407
Chickpet                405
KR Puram                404
Richmond Town           404
Jayanagar               404
Basavanagudi            402
Kammanahalli            402
Padmanabhanagar         401
Nagarbhavi              399
Magadi Road             397
Yeshwanthpur            394
Frazer Town             394
Banashankari            394
Ulsoor                  393
Whitefield              390
Ramamurthy Nagar        386
Chamarajpet             385
Cox Town                384
Indiranagar             383
Devanahalli             383
Hulimavu                383
Yelahanka               381
Bellandur               369
Varthur                 365
Name: count, dtype: int64

## Text Data Cleaning

In [25]:
text_cols=df.select_dtypes(include='object').columns

for col in text_cols:
    df[col]=df[col].astype("string").str.strip()

print("data cleaning completed successfully")

data cleaning completed successfully

In [26]:
print(df.head())

                 Date      Time     Booking_ID        Booking_Status  \
0 2024-07-26 14:00:00  14:00:00  CNR7153255142    Canceled by Driver
1 2024-07-25 22:20:00  22:20:00  CNR2940424040               Success
2 2024-07-30 19:59:00  19:59:00  CNR2982357879               Success
3 2024-07-22 03:15:00  03:15:00  CNR2395710036  Canceled by Customer
4 2024-07-02 09:02:00  09:02:00  CNR1797421769               Success

  Customer_ID Vehicle_Type Pickup_Location Drop_Location  V_TAT  C_TAT  \
0   CID713523  Prime Sedan     Tumkur Road      RT Nagar    0.0    0.0
1   CID225428         Bike     Magadi Road       Varthur  203.0   30.0
2   CID270156    Prime SUV   Sahakar Nagar       Varthur  238.0  130.0
3   CID581320        eBike      HSR Layout   Vijayanagar    0.0    0.0
4   CID939555         Mini     Rajajinagar   Chamarajpet  252.0   80.0

                     Canceled_Rides_by_Customer      Canceled_Rides_by_Driver  \
0                                Not Applicable  Personal & Car related issue
1                                Not Applicable                Not Applicable
2                                Not Applicable                Not Applicable
3  Driver is not moving towards pickup location                Not Applicable
4                                Not Applicable                Not Applicable

  Incomplete_Rides Incomplete_Rides_Reason  Booking_Value  Payment_Method  \
0               No          Not Applicable            444  Not Applicable
1               No          Not Applicable            158            Cash
2               No          Not Applicable            386             UPI
3               No          Not Applicable            384  Not Applicable
4               No          Not Applicable            822     Credit Card

   Ride_Distance  Driver_Ratings  Customer_Rating
0              0             0.0              0.0
1             13             4.1              4.0
2             40             4.2              4.8
3              0             0.0              0.0
4             45             4.0              3.0

In [27]:
print(text_cols)

Index(['Time', 'Booking_ID', 'Booking_Status', 'Customer_ID', 'Vehicle_Type',
       'Pickup_Location', 'Drop_Location', 'Canceled_Rides_by_Customer',
       'Canceled_Rides_by_Driver', 'Incomplete_Rides',
       'Incomplete_Rides_Reason', 'Payment_Method'],
      dtype='object')

 ## Date and Time Cleaning

In [28]:
df['Date']=pd.to_datetime(df['Date'],errors='coerce')

In [29]:
df["Time"]=pd.to_datetime(df['Time'].astype(str),errors="coerce").dt.time

C:\Users\HP\AppData\Local\Temp\ipykernel_7824\1570105618.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Time"]=pd.to_datetime(df['Time'].astype(str),errors="coerce").dt.time

In [30]:
df["Date"] = pd.to_datetime(df["Date"]).dt.date
#df

## Check Numeric Columns

In [31]:
numeric_cols=[
    'V_TAT',
    'C_TAT',
    'Booking_Value',
    'Ride_Distance',
    'Driver_Ratings',
    'Customer_Rating'
]
for col in numeric_cols:
    df[col]=pd.to_numeric(df[col],errors='coerce')

In [32]:
df[numeric_cols].dtypes

V_TAT              float64
C_TAT              float64
Booking_Value        int64
Ride_Distance        int64
Driver_Ratings     float64
Customer_Rating    float64
dtype: object

##  Impossible Values Check

In [33]:
df[df["Ride_Distance"]<0]

Empty DataFrame
Columns: [Date, Time, Booking_ID, Booking_Status, Customer_ID, Vehicle_Type, Pickup_Location, Drop_Location, V_TAT, C_TAT, Canceled_Rides_by_Customer, Canceled_Rides_by_Driver, Incomplete_Rides, Incomplete_Rides_Reason, Booking_Value, Payment_Method, Ride_Distance, Driver_Ratings, Customer_Rating]
Index: []

In [34]:
df[df["Booking_Value"]<0]

Empty DataFrame
Columns: [Date, Time, Booking_ID, Booking_Status, Customer_ID, Vehicle_Type, Pickup_Location, Drop_Location, V_TAT, C_TAT, Canceled_Rides_by_Customer, Canceled_Rides_by_Driver, Incomplete_Rides, Incomplete_Rides_Reason, Booking_Value, Payment_Method, Ride_Distance, Driver_Ratings, Customer_Rating]
Index: []

In [35]:
df[(df["Driver_Ratings"]<0) | (df["Driver_Ratings"] >5)]

Empty DataFrame
Columns: [Date, Time, Booking_ID, Booking_Status, Customer_ID, Vehicle_Type, Pickup_Location, Drop_Location, V_TAT, C_TAT, Canceled_Rides_by_Customer, Canceled_Rides_by_Driver, Incomplete_Rides, Incomplete_Rides_Reason, Booking_Value, Payment_Method, Ride_Distance, Driver_Ratings, Customer_Rating]
Index: []

In [36]:
df[(df["Customer_Rating"]<0) | (df["Customer_Rating"] >5)]

Empty DataFrame
Columns: [Date, Time, Booking_ID, Booking_Status, Customer_ID, Vehicle_Type, Pickup_Location, Drop_Location, V_TAT, C_TAT, Canceled_Rides_by_Customer, Canceled_Rides_by_Driver, Incomplete_Rides, Incomplete_Rides_Reason, Booking_Value, Payment_Method, Ride_Distance, Driver_Ratings, Customer_Rating]
Index: []

## Zero Distance Check

In [37]:
df[df["Ride_Distance"]==0]

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
0,2024-07-26,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,0.0,0.0,Not Applicable,Personal & Car related issue,No,Not Applicable,444,Not Applicable,0,0.0,0.0
3,2024-07-22,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,0.0,0.0,Driver is not moving towards pickup location,Not Applicable,No,Not Applicable,384,Not Applicable,0,0.0,0.0
7,2024-07-11,11:12:00,CNR5374902489,Canceled by Driver,CID735691,Prime Plus,Bannerghatta Road,Sarjapur Road,0.0,0.0,Not Applicable,Personal & Car related issue,No,Not Applicable,344,Not Applicable,0,0.0,0.0
8,2024-07-01,19:19:00,CNR5030602354,Driver Not Found,CID999840,Mini,Chamarajpet,Peenya,0.0,0.0,Not Applicable,Not Applicable,No,Not Applicable,839,Not Applicable,0,0.0,0.0
9,2024-07-18,01:31:00,CNR6328453219,Canceled by Driver,CID907133,Auto,RT Nagar,Varthur,0.0,0.0,Not Applicable,Personal & Car related issue,No,Not Applicable,893,Not Applicable,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20395,2024-07-29,04:14:00,CNR5886368174,Driver Not Found,CID921441,Prime Plus,Magadi Road,Kammanahalli,0.0,0.0,Not Applicable,Not Applicable,No,Not Applicable,1690,Not Applicable,0,0.0,0.0
20399,2024-07-11,21:31:00,CNR4399533433,Canceled by Driver,CID745127,eBike,Hennur,Mysore Road,0.0,0.0,Not Applicable,Personal & Car related issue,No,Not Applicable,446,Not Applicable,0,0.0,0.0
20401,2024-07-17,07:09:00,CNR8367338252,Canceled by Driver,CID923413,Mini,JP Nagar,Varthur,0.0,0.0,Not Applicable,More than permitted people in there,No,Not Applicable,615,Not Applicable,0,0.0,0.0
20402,2024-07-27,19:46:00,CNR9637947510,Canceled by Customer,CID868443,Prime SUV,Richmond Town,Whitefield,0.0,0.0,AC is Not working,Not Applicable,No,Not Applicable,303,Not Applicable,0,0.0,0.0
20406,2024-07-17,02:53:00,CNR4049412680,Canceled by Driver,CID420033,Prime Sedan,JP Nagar,Shantinagar,0.0,0.0,Not Applicable,Customer was coughing/sick,No,Not Applicable,533,Not Applicable,0,0.0,0.0

In [38]:
pd.crosstab(df["Booking_Status"], df["Ride_Distance"] == 0)

Ride_Distance         False  True
Booking_Status
Canceled by Customer      0   2081
Canceled by Driver        0   3654
Driver Not Found          0   2020
Success               12652      0

##  Booking ID Duplicate Check

In [39]:
df["Booking_ID"].duplicated().sum()

np.int64(0)

In [40]:
df[df["Booking_ID"].duplicated(keep=False)]

Empty DataFrame
Columns: [Date, Time, Booking_ID, Booking_Status, Customer_ID, Vehicle_Type, Pickup_Location, Drop_Location, V_TAT, C_TAT, Canceled_Rides_by_Customer, Canceled_Rides_by_Driver, Incomplete_Rides, Incomplete_Rides_Reason, Booking_Value, Payment_Method, Ride_Distance, Driver_Ratings, Customer_Rating]
Index: []

## Customer ID Check

In [41]:
df["Customer_ID"].isnull().sum()

np.int64(0)

In [42]:
df["Customer_ID"].unique()

<StringArray>
['CID713523', 'CID225428', 'CID270156', 'CID581320', 'CID939555', 'CID802429',
 'CID476071', 'CID735691', 'CID999840', 'CID907133',
 ...
 'CID142264', 'CID231191', 'CID745127', 'CID124345', 'CID923413', 'CID868443',
 'CID902638', 'CID214557', 'CID110375', 'CID420033']
Length: 20189, dtype: string

## Add New Analytical Columns

In [43]:
df["Month"] = pd.to_datetime(df["Date"]).dt.month_name()

In [44]:
df["Day"] = pd.to_datetime(df["Date"]).dt.day_name()

In [45]:
df["Hour"]=pd.to_datetime(df["Time"].astype(str),errors="coerce").dt.hour

C:\Users\HP\AppData\Local\Temp\ipykernel_7824\1630076830.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Hour"]=pd.to_datetime(df["Time"].astype(str),errors="coerce").dt.hour

In [46]:
df.to_csv("Ola_Cleaned_Data.csv", index=False)

print("Cleaned dataset saved successfully")

Cleaned dataset saved successfully

In [47]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\hp\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\hp\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: greenlet>=1 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [48]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:shital593@localhost/ola_ride_analytics"
)

In [49]:
#Connect data to my sql

from sqlalchemy import text

with engine.connect() as connection:
    result = connection.execute(text("SELECT 1"))
    print("MySQL Connected Successfully!")

MySQL Connected Successfully!

In [50]:
# send data to mysql

df.to_sql(
    "ola_bookings",  #table
    con=engine,
    if_exists="replace",
    index=False
)

20407